var games = {
  "bunny-clicker":{name:"Bunny Clicker",author:"orteil",tags:["animals"],release:"2017-07-25"},
  "fake-money-clicker":{name:"Fake Money Clicker",author:"fractyl",tags:["economy","pyigmg","joke"],release:"2024-05-05"},
  "milk-game":{name:"Get a Glass of Milk Because You Have To",author:"rylie-eric",tags:["food","story"],release:"2021-08-24"},
  "space-station-manager":{name:"Space Station Manager",author:"kasperja",tags:["space","pyigmg","technology"],release:"2022-08-19"},
  "literally-watch-paint-dry":{name:"Literally Watch Paint Dry",author:"rylie-eric",tags:["story"],release:"2022-04-23"},
  "hellion-scarab":{name:"Hellion Scarab",author:"kasperja",tags:["space","pyigmg","technology"],release:"2022-08-30"},
  "cargohold-idle":{name:"CargoHold Idle",author:"kasperja",tags:["space","economy","technology"],release:"2025-04-02"},
  "become-rich":{name:"become Rich !!!!",author:"boshki",tags:["economy","joke"],release:"2022-08-21"},
  "a-frozen-christmas":{name:"A Frozen Christmas",author:"boshki",tags:["igm-game-jam","game-jam","christmas"],release:"2025-12-29"},
  "the-lost-labyrinths":{name:"The Lost Labyrinths",author:"lg",tags:["pyigmg","rpg"],release:"2022-08-24",related:["labyrinths-ii"]},
  "labyrinths-ii":{name:"Labyrinths II",author:"lg",tags:["rpg"],release:"2025-05-24",related:["the-lost-labyrinths"]},
  "stone-mine-simulator-2024":{name:"Stone Mine Simulator 2024",author:"lg",tags:["mining","pyigmg"],release:"2024-08-08",related:["stone-mine-simulator","stone-mine-simulator-2"]},
  "forezs-dream":{name:"Forez's Dream",author:"frenzy",tags:["rpg","pyigmg"],release:"2021-01-28"},
  "soviet-clicker":{name:"Soviet Clicker",author:"fractyl",tags:["history"],release:"2024-05-05"},
  "christpoly":{name:"Christpoly",author:"frenzy",tags:["igm-game-jam","game-jam","christmas"],release:"2025-12-25"},
  "waves":{name:"Waves",author:"frenzy",tags:["rpg"],release:"2025-03-26"},
  "cake-clicker":{name:"Cake Clicker (2022)",author:"fractyl",tags:["food"],release:"2022-09-26",related:["cake-clicker-old"]},
  "cake-clicker-old":{name:"Cake Clicker (old)",author:"fractyl",tags:["food"],release:"2021-09-01",related:["cake-clicker"]},
  "christmas-cheer-clicker":{name:"Christmas Cheer Clicker",author:"fractyl",tags:["igm-game-jam","game-jam","christmas"],release:"2025-12-25"},
  "coin-mania":{name:"Coin Mania",author:"irondizaster",tags:["economy"],release:"2024-03-03"},
  "tycoon-simulator":{name:"Tycoon Simulator",author:"irondizaster",tags:["economy"],release:"2022-02-26"},
  "five":{name:"Five",author:"hyphen",tags:["joke","5"],release:"2023-06-02"},
  "lemonade-clicker":{name:"Lemonade Clicker",author:"hyphen",tags:["food"],release:"2023-03-15"},
  "item-clicker":{name:"Item Clicker",author:"hyphen",tags:["technology"],release:"2022-09-24"},
  "after-hours-x":{name:"After Hours X",author:"lg",tags:["igm-game-jam","game-jam","christmas","horror"],release:"2025-12-29"},
  "ice-cream-clicker":{name:"Ice Cream Clicker",author:"2slimes",tags:["food"],release:"2022-03-30"},
  "color-clicker":{name:"Color Clicker",author:"2slimes",tags:["no-other-tags"],release:"2022-07-15"},
  "fire-forge-old":{name:"Fire Forge (old)",author:"lg",tags:["story"],release:"2022-07-15"},
  "the-spinoff-game":{name:"The Spinoff Game",author:"fractyl",tags:["joke"],release:"2024-06-26"},
  "stone-mine-simulator":{name:"Stone Mine Simulator",author:"lg",tags:["mining"],release:"2019",related:["stone-mine-simulator-2","stone-mine-simulator-2024"]},
  "stone-mine-simulator-2":{name:"Stone Mine Simulator 2",author:"lg",tags:["mining"],release:"2022-02-15",related:["stone-mine-simulator","stone-mine-simulator-2024"]},
  "wall-destroyer":{name:"Wall Destroyer",author:"luri",tags:["old-igm","story"],release:"2014-05-02"},
  "clacker":{name:"Clacker",author:"killerboib",tags:["technology","educational"],release:"2024-09-20"},
  "wood-clicker-digital":{name:"Wood Clicker Digital",author:"aeries18",tags:["pyigmg"],release:"2024-07-26"},
  "water-hoarder":{name:"Water Hoarder",author:"bilingualistic",tags:["food"],release:"2023-04-29"},
  "x-squared":{name:"X Squared",author:"scrambledrubiks",tags:["mathematics"],release:"2013-07-26"},
  "rocket-game":{name:"Rocket Game",author:"hyphen",tags:["space","technology"],release:"2023-06-02"},
  "phone-maker":{name:"Phone Maker",author:"tgrein",tags:["technology"],release:"2022-04-08",related:["phone-maker-2"]},
  "phone-maker-2":{name:"Phone Maker 2",author:"tgrein",tags:["technology"],release:"2022-11-01",related:["phone-maker"]},
  "factory-maker":{name:"Factory Maker",author:"tgrein",tags:["no-other-tags"],release:"2022-10-08"},
  "burger-clicker":{name:"Burger Clicker",author:"orteil",tags:["food","old-igm"],release:"2014-01-02"},
  "mushroom-clicker":{name:"Mushroom Clicker",author:"sage",tags:["food","game-jam"],release:"2024-10-21"},
  "loft-clicker":{name:"Loft Clicker",author:"arandomexican",tags:["food","animals"],release:"2025-01-28"},
  "shopping-mall-tycoon":{name:"Shopping Mall Tycoon",author:"dtji-psimfans",tags:["business"],release:"2018-04-27"},
  "modern-house-tycoon":{name:"Modern House Tycoon",author:"dtji-psimfans",tags:["business"],release:"2018-04-08"},
  "airport-manager":{name:"Airport Manager",author:"dtji-psimfans",tags:["business"],release:"2018-02-22"},
  "travel-agency-manager":{name:"Travel Agency Manager",author:"dtji-psimfans",tags:["business"],release:"2018-02-18"},
  "countryside-construction":{name:"Countryside Construction",author:"dtji-psimfans",tags:["business"],release:"2018-04-01"},
  "block-clicker":{name:"Block Clicker",author:"dtji-psimfans",tags:["no-other-tags"],release:"2018-02-15"},
  "lucky-guess":{name:"Lucky Guess",author:"dtji-psimfans",tags:["no-other-tags"],release:"2018-10-31"},
  "table-clicker":{name:"Table Clicker",author:"zelo101",tags:["no-other-tags"],release:"2017-10-26"},
  "recursive-upgrades":{name:"Recursive Upgrades",author:"humble-run1643",tags:["no-other-tags"],release:"2026-06-18"},
  "qr-code-clicker":{name:"QR Code Clicker",author:"sunnystew",tags:["no-other-tags"],release:"2023-01-26"},
  "dog-clicker":{name:"Dog Clicker",author:"arandomexican",tags:["animals"],release:"2024-03-27"},
  "human-clicker":{name:"Human Clicker",author:"kaarnij666",tags:["civilization"],release:"2022-09-15"},
  "chicken-farmer":{name:"Chicken Farmer",author:"davtalas",tags:["animals"],release:"2024-06-09"},
  "idle-hero":{name:"Idle Hero",author:"davtalas",tags:["rpg"],release:"2024-12-18"},
  "pizza-baker":{name:"Pizza Baker",author:"jez",tags:["food"],release:"2023-10-11"},
}
var authors = {
  "fractyl":{name:"Fractyl", aka:["Fractylizer","Amethyst"]},
  "rylie-eric":{name:"Rylie Eric", aka:["Agentperson","AgentRylie"]},
  "kasperja":{name:"Kasperja"},
  "boshki":{name:"Boshki0987"},
  "frenzy":{name:"FragileFrenzY", aka:["DomNite","Frenzy"]},
  "lg":{name:"LG", aka:["LGPlayer13","LG Productions"]},
  "hyphen":{name:"Hyphen", aka:["hyphen-lost","Lexal","Lexali5","Haloscarf Games"]},
  "sage":{name:"Sage", aka:["themeowingsage"]},
  "2slimes":{name:"2 Slimes", aka:["Two Slimes","TheodoreHHH"]},
  "irondizaster":{name:"IronDizaster"},
  "tgrein":{name:"TGRein", aka:["Rein"]},
  "orteil":{name:"Orteil", aka:["Orteil42","Julien Thiennot"]},
  "luri":{name:"Luri", aka:["Tellurium"]},
  "dtji-psimfans":{name:"Dtji Psimfans"},
  "zelo101":{name:"Zelo101"},
  "scrambledrubiks":{name:"ScrambledRubiks"},
  "humble-run1643":{name:"Humble-Run1643"},
  "sunnystew":{name:"SunnyStew", aka:["SunnyStew22"]},
  "killerboib":{name:"killerboib", aka:["George"]},
  "aeries18":{name:"Aeries18"},
  "arandomexican":{name:"ARandoMexican"},
  "kaarnij666":{name:"KaarNij666"},
  "bilingualistic":{name:"Bilingualistic"},
  "davtalas":{name:"Davtalas"},
  "jez":{name:"Jez"},
}
var tags = {
  "space":{desc:"Game about space and/or set in space."},
  "economy":{desc:"Games focused around money and/or the economy."},
  "food":{desc:"Games focused around food and/or drink."},
  "story":{desc:"Games with a significant story/lore element."},
  "pyigmg":{desc:"Games featured on <a href=\"/?a=irondizaster\">IronDizaster</a>'s <cite><a href=\"?p=irondizaster-pyigmg\">Playing Your Idle Game Maker Games</a></cite> series."},
  "game-jam":{desc:"Games created as part of a game jam."},
  "igm-game-jam":{desc:"Games created for an IGM game jam."},
  "christmas":{desc:"Games themed around Christmas."},
  "mining":{desc:"Games about mining."},
  "rpg":{desc:"RPGs and games inspired by RPGs."},
  "joke":{desc:"Games based on a silly concept that take themselves mostly humourously."},
  "5":{desc:"Games about 5."},
  "horror":{desc:"Scary games!"},
  "technology":{desc:"Games based on or themed around technology."},
  "animals":{desc:"Games about animals."},
  "old-igm":{desc:"Games created using the old prototype version of IGM."},
  "business":{desc:"Games about the management of a business."},
  "mathematics":{desc:"Games about mathematics."},
  "educational":{desc:"Educational games."},
  "history":{desc:"Games set in the past."},
  "no-other-tags":{desc:"Games with no other tags."},
}
var pages = [
  "about",
  "igm-game-jam-2025",
  "authors",
  "games"
]

